name: fluttermixpanel_example
description: Demonstrates how to use the fluttermixpanel plugin.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  fluttermixpanel:
    path: ../

flutter:
  uses-material-design: true
